### ISSUE TITLE
Character page (team members)

### ISSUE THREAD

**Issue by infurnodragon** [Vanier-Robotics/robotics-2020#14]
Includes `nav` menu. Layout on Discord.

**Comment by Cryotechnic** [comment]
Preferably someone who knows what they are doing and feel confident enough to take this on.

**Comment by Cryotechnic** [comment]
Will need to be properly scaled as we get exact member count per team.

**Comment by Cryotechnic** [comment]
Scaling is simple, page is content-ready. Closing.
