### ISSUE TITLE
Game page (tutorial page)

### ISSUE THREAD

**Issue by infurnodragon** [Vanier-Robotics/robotics-2020#17]
Includes `nav` menu, parallax. Layout on Discord. (refer to rule book).

**Comment by Cryotechnic** [comment]
Video player is not being displayed at full height. Needs further development, but the rest is ready and the page is, apart from that issue, content-ready.

**Comment by Cryotechnic** [comment]
Video player issue fixed. Page is now content-ready, closing issue.
